# Typos configuration file

[default]
extend-ignore-re = [
  # Add regex patterns to ignore specific cases here
  "\\$2[ayb]\\$[0-9]{2}\\$[A-Za-z0-9./]{53}",  # bcrypt hashes
  "secret='[^']+'",  # secret assignments with single quotes
  "secret=\"[^\"]+\"",  # secret assignments with double quotes
  "id='[A-Za-z0-9]{60,}'",  # OIDC client IDs with single quotes
  "id=\"[A-Za-z0-9]{60,}\"",  # OIDC client IDs with double quotes
  "SET id='[A-Za-z0-9]+',\\s*secret='\\$2[ayb]\\$[0-9]{2}\\$[A-Za-z0-9./]+'",  # Full SQL SET statements
]

[files]
extend-exclude = [
  # Add filenames or patterns to exclude from checking
  "package-lock.json",
  "node_modules/",
  ".docusaurus/",
  "build/"
]